### ISSUE TITLE
Second Level Retries Exception - Object serialized to Boolean. RavenJObject instance expected.

### ISSUE THREAD

**Issue by jpv001** [Particular/NServiceBus.RavenDB#254]
I've got a few failed messages in ServiceInsight that look to have been caused by the second level retry mechanism. The message I'm sending looks like this:

```
{
  "Id":"e2984c33-f7b6-46c5-92e7-917a88f680a6",
  "PaymentType":4,
  "PaidOnUtc":"2016-06-20T00:00:00",
  "CurrencyRate":1,
  "Amount":50,
  "Reference":"1111",
  "AccountInvoiceId":"creditor/1/accountinvoice/64cd559e-8e03-46af-b461-8555285cee71",
  "IsDeleted":false,
  "IsVoid":false,
  "PaymentStatus":40
}
```

Exception: Object serialized to Boolean. RavenJObject instance expected.

Stack Trace:
```
System.ArgumentException: Object serialized to Boolean. RavenJObject instance expected.
   at Raven.Json.Linq.RavenJObject.FromObject(Object o, JsonSerializer jsonSerializer) in C:\Builds\RavenDB-3.5-Unstable\Raven.Abstractions\Json\Linq\RavenJObject.cs:line 177
   at Raven.Client.Document.EntityToJson.GetObjectAsJson(Object entity) in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\EntityToJson.cs:line 72
   at Raven.Client.Document.EntityToJson.ConvertEntityToJson(String key, Object entity, RavenJObject metadata) in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\EntityToJson.cs:line 44
   at Raven.Client.Document.InMemoryDocumentSessionOperations.EntityChanged(Object entity, DocumentMetadata documentMetadata, IDictionary`2 changes) in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 1187
   at Raven.Client.Document.InMemoryDocumentSessionOperations.<PrepareForEntitiesPuts>b__108_0(KeyValuePair`2 pair) in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 1002
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Raven.Client.Document.InMemoryDocumentSessionOperations.PrepareForEntitiesPuts(SaveChangesData result) in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 1002
   at Raven.Client.Document.InMemoryDocumentSessionOperations.PrepareForSaveChanges() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 984
   at Raven.Client.Document.Async.AsyncDocumentSession.<SaveChangesAsync>d__72.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\Async\AsyncDocumentSession.cs:line 916
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.FirstLevelRetriesBehavior.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Recoverability\FirstLevelRetries\FirstLevelRetriesBehavior.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at NServiceBus.FirstLevelRetriesBehavior.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Recoverability\FirstLevelRetries\FirstLevelRetriesBehavior.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.SecondLevelRetriesBehavior.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Recoverability\SecondLevelRetries\SecondLevelRetriesBehavior.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.SecondLevelRetriesBehavior.<DeferMessageForSecondLevelRetry>d__2.MoveNext() in C:\Build\src\NServiceBus.Core\Recoverability\SecondLevelRetries\SecondLevelRetriesBehavior.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.SecondLevelRetriesBehavior.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Recoverability\SecondLevelRetries\SecondLevelRetriesBehavior.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MoveFaultsToErrorQueueBehavior.<Invoke>d__3.MoveNext() in C:\Build\src\NServiceBus.Core\Recoverability\Faults\MoveFaultsToErrorQueueBehavior.cs:line 37
```

The setup is using the Raven 3.5 beta and the NSB latest version of both NSB.RavenDb and NSB core. This isn't a critical issue as it's on all beta stuff, just a heads up.

**Comment by DavidBoike** [comment]
@jpv001 Thanks! I reformatted your text a little to make it readable so my brain could make better sense of it. It's worth noting that I pretty-formatted the JSON. IRL it was standard, non-indented JSON.

By "NSB latest version" you mean latest released versions, not the V6 betas, correct?

**Comment by DavidBoike** [comment]
Nevermind, looking at the stack trace full of TaskAwaiter it's clear you must mean NSB betas as well. Sorry!

**Comment by jpv001** [comment]
Sorry yes, we're checking out the beta of both at the same time, living
life on the edge as it were. Thanks for cleaning up the formatting, it was
a bit of a rush job.

**Comment by DavidBoike** [comment]
@jpv001 Are you using the Outbox feature? And if so, can you look up an outbox record document corresponding to one of the message ids that failed?

**Comment by jpv001** [comment]
Yes we are using the Outbox feature, but the record doesn't seem to exist, looking for the outbox/endpointname/messageid doesn't yield any results. I'll keep an eye out for another one and see if we can catch it in the act. This wasn't an isolated case, there were 7 other messages of the same type that hit the same issue.

**Comment by jpv001** [comment]
Closing this as the root cause was found to be a middle tier not serialising the raven object correctly, it's not an NSB.RavenDb issue.
