### ISSUE TITLE
Endpoints crash after a few days of operation using RavenDb Outbox

### ISSUE THREAD

**Issue by jpv001** [Particular/NServiceBus.RavenDB#255]
Endpoints using the RavenDb Outbox crash after about a day or two, this has been happening consistently on all of our self-hosted endpoints while using the following builds (the latest betas):

NServiceBus.RavenDB 4.0.0-beta0005
RavenDB.Client 3.5.0-rc-35157
NServiceBus 6.0.0-beta0004

It seems to be related to the Outbox cleanup that takes care of the completed messages. Something to note is that they don't all crash at the same time, they fail a few at a time. All of the endpoints have their own databases and are started around the same time by our build process. Even endpoints that have no messages in their outbox collections (as in the endpoint wasn't used at all) crash.

Once they're started again they keep going for around the same period of time working perfectly until they hit this cleanup again and die.

```
Unhandled Exception: Raven.Abstractions.Connection.ErrorResponseException: A task was canceled.
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<>c__DisplayClass36_0.<<SendRequestInternal>b__0>d.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Connection\Implementation\HttpJsonRequest.cs:line 256
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<RunWithAuthRetry>d__38`1.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Connection\Implementation\HttpJsonRequest.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Implementation.HttpJsonRequest.<ReadResponseJsonAsync>d__35.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Connection\Implementation\HttpJsonRequest.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Util.Auth.SingleAuthTokenRetriever.<GetToken>d__6.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Util\Auth\SingleAuthTokenRetriever.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Raven.Client.Connection.Async.AsyncServerClient.<DirectStreamQueryAsync>d__129.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Connection\Async\AsyncServerClient.cs:line 1935
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.ReplicationInformerBase`1.<TryOperationAsync>d__34`1.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Connection\ReplicationInformerBase.cs:line 409
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Raven.Client.Connection.ReplicationInformerBase`1.<ExecuteWithReplicationAsync>d__33`1.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Connection\ReplicationInformerBase.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Connection.Async.AsyncServerClient.<ExecuteWithReplication>d__155`1.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Connection\Async\AsyncServerClient.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Document.Async.AsyncDocumentSession.<StreamAsync>d__37`1.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\Async\AsyncDocumentSession.cs:line 415
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Document.Async.AsyncDocumentSession.<StreamAsync>d__36`1.MoveNext() in C:\Builds\RavenDB-3.5-Unstable\Raven.Client.Lightweight\Document\Async\AsyncDocumentSession.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Persistence.RavenDB.OutboxRecordsCleaner.<RemoveEntriesOlderThan>d__1.MoveNext() in C:\Build\src\NServiceBus.RavenDB\Outbox\OutboxRecordsCleaner.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Persistence.RavenDB.RavenDbOutboxStorage.OutboxCleaner.PerformCleanup(Object state) in C:\Build\src\NServiceBus.RavenDB\Outbox\RavenDbOutboxStorage.cs:line 76
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

**Comment by DavidBoike** [comment]
Thanks for the report @jpv001. Not sure I trust the streaming query for batch deletes like this.

I pushed up a PR to fix this in #256.

**Comment by jpv001** [comment]
Awesome response, the new implementation is a lot cleaner. I'll give it a spin as soon as it hits the package.

**Comment by DavidBoike** [comment]
This will be in the next beta package, should be `NServiceBus.RavenDB 4.0.0-beta0006`.

**Comment by mauroservienti** [comment]
@jpv001 the PR is merged and the package has been released as `NServiceBus.RavenDB 4.0.0-beta0006` on MyGet, it will be soon on Nuget. I'll close this one.
