### ISSUE TITLE
When starting NSB 4.6.1 on Asp.net MVC, RavenDB (403) Forbidden

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#48]
Raised by @danielHalan
Migrated from by https://github.com/Particular/NServiceBus/issues/2144

Getting following exception when Starting NSB on an ASP.NET MVC Instance, at Configure.With()....ForMvc()...RavenPersistence().RavenSubscriptionStorage()....
.UnicastBus()
             .LoadMessageHandlers()
.CreateBus()

And http://xx:8080 is up n running.

System.WebException "The remote server returned an error: (403) Forbidden."

```
   at System.Net.HttpWebRequest.GetResponse()
   at Raven.Client.Connection.HttpJsonRequest.ReadJsonInternal(Func`1 getResponse) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Connection\HttpJsonRequest.cs:line 341
   at Raven.Client.Connection.HttpJsonRequest.ReadResponseJson() in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Connection\HttpJsonRequest.cs:line 244
   at Raven.Client.Connection.ServerClient.DirectPut(RavenJObject metadata, String key, Nullable`1 etag, RavenJObject document, String operationUrl) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Connection\ServerClient.cs:line 398
   at Raven.Client.Connection.ServerClient.<>c__DisplayClass13.<Put>b__12(String u) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Connection\ServerClient.cs:line 333
   at Raven.Client.Connection.ReplicationInformer.TryOperation[T](Func`2 operation, String operationUrl, Boolean avoidThrowing, T& result) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Connection\ReplicationInformer.cs:line 564
   at Raven.Client.Connection.ReplicationInformer.ExecuteWithReplication[T](String method, String primaryUrl, Int32 currentRequest, Int32 currentReadStripingBase, Func`2 operation) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Connection\ReplicationInformer.cs:line 523
   at Raven.Client.Connection.ServerClient.ExecuteWithReplication[T](String method, Func`2 operation) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Connection\ServerClient.cs:line 174
   at Raven.Client.Connection.ServerClient.Put(String key, Nullable`1 etag, RavenJObject document, RavenJObject metadata) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Connection\ServerClient.cs:line 333
```

![image](https://cloud.githubusercontent.com/assets/641348/3138484/cdb11e02-e892-11e3-8a28-b661b042d8a5.png)

**Comment by johnsimons** [comment]
This is related to https://github.com/Particular/Requirements/issues/131

**Comment by danielmarbach** [comment]
Is this still an issue or can we close?

**Comment by elovelan** [comment]
I'll verify

**Comment by danielmarbach** [comment]
@elovelan any updates on this?

**Comment by elovelan** [comment]
@danielmarbach, can you please give me some more details as to which version this was fixed in? Was it in a version of NSB 4, NSB.Raven 2 or an NSB 5 version?

Also, I saw this issue when I was originally trying to host a publisher in an MVC app which is generally [not the best idea](http://docs.particular.net/nservicebus/hosting/publishing-from-web-applications) so even if this isn't fixed, maybe the right idea is to include this as another reason not to host a publisher in an IIS process.

**Comment by danielmarbach** [comment]
@elovelan if you are on RavenDB 2.5 then use NServiceBus.RavenDB 2.2, ok?

**Comment by mauroservienti** [comment]
Is this still an issue?

**Comment by elovelan** [comment]
I haven't tested it in a while but I'll happily check it out
