### ISSUE TITLE
Providing custom session is broken

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.RavenDB#71]
The `UseSharedSession` API is broken and using it prevents the endpoint from starting. I propose we fix it according to https://github.com/Particular/Requirements/issues/258:
- [x] Expose the shared session (one opened by `OpenSessionBehavior`) always, not only when Saga/Outbox are enabled
- [x] Make that session lazy i.e. it will be only opened if somebody accesses it 
- [x] Provide a method that would allow the user to create the session and use that medhod in `OpenSessionBehavior`. The session created via user-provide callback would still be managed by NSB, same as the 'normal' session.
- [x] Ensure the session is committed the same as NSB opened session

Connects to https://github.com/Particular/PlatformDevelopment/issues/733

**Comment by ramonsmits** [comment]
To add to that:

- When calling `UseSharedSession` then saga and outbox persistence results in runtime exception when these persisters are build by the container.


The `ISessionProvider` works when:
- You *not* calling `UseSharedSession` *and* saga or outbox persisters are active then an `ISessionProvider` is injected in the message handler
- `ISessionProvider.Session` cannot be called in a handlers constructor

**Comment by colin-higgins** [comment]
I think this has been mostly handled in the latest code on `develop`.

The only thing that does not align is management of the unit of work.

You said 
> The session created via user-provide callback would still be managed by NSB, same as the 'normal' session.

What does that mean exactly? That we would be responsible for opening and committing a unit of work? That seems to conflict with what we did for synchronized storage session.

**Comment by SzymonPobiega** [comment]
@colin-higgins In NHibernate we actually removed the API for providing a session because it was broken :( I meant here that if there is a callback we use to get a session from the user, we should dispose it just like the session created by us.

**Comment by colin-higgins** [comment]
If we dispose it though that would mean we should also commit it before that, right?
It does seem like it adds a lot of complexity for not much gain... Particularly in the conventions that @DavidBoike has been working on. We need to do a lot to make sure that the conventions align in user provided session scenarios.

**Comment by SzymonPobiega** [comment]
@colin-higgins the "old" custom session API

```
public static PersistenceExtentions<RavenDBPersistence> UseSharedSession(
   this PersistenceExtentions<RavenDBPersistence> cfg, 
   Func<IDocumentSession> getSessionFunc)
```

uses a `Func` in such a way that the "thing" that provides the session can't really commit the changes. This is what I meant saying that NSB has to commit and close such a session.

**Comment by colin-higgins** [comment]
Then that means we did it wrong and need to fix it.  
PING @DavidBoike @kbaley

**Comment by DavidBoike** [comment]
In what versions are we talking here?

**Comment by colin-higgins** [comment]
It pretty much didn't work at all before the version we had in develop.

**Comment by DavidBoike** [comment]
What I mean is are we talking about changing develop, or backporting a fix to older versions as well?

**Comment by colin-higgins** [comment]
only develop

**Comment by DavidBoike** [comment]
OK, should we add to PoA for Particular/PlatformDevelopment#733?

**Comment by ramonsmits** [comment]
Reopening this as the issue does not seem to be fixed and no reason for closing was mentioned. As the API is still present I suspect it should work. 

- https://discuss.particular.net/t/nsb-5-raven-msmq-when-moving-to-outbox-shouldnt-we-be-using-a-shared-document-session/293/3

Either the API must work, or throw an `NotSupportException` mentioning that the API isn't supported/is obsolete.

## Packages:

- NServiceBus 5.2.25
- NServiceBus.RavenDB 3.2.2


## Exception

```
2018-01-08 17:49:45.857 INFO  NServiceBus.Unicast.Transport.TransportReceiver Failed to process message
Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NServiceBus.SagaPersisters.RavenDB.SagaPersister' can be invoked with the available services and parameters:
Cannot resolve parameter 'NServiceBus.RavenDB.Persistence.ISessionProvider sessionProvider' of constructor 'Void .ctor(NServiceBus.RavenDB.Persistence.ISessionProvider)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringPropertyInjector.InjectProperties(IComponentContext context, Object instance, Boolean overrideSetValues)
   at Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1 parameters, Object& instance)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at NServiceBus.ObjectBuilder.Autofac.AutofacObjectBuilder.Build(Type typeToBuild)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.SetCurrentMessageBeingHandledBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.LoadHandlersBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.InvokeSagaNotFoundBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.ExecuteLogicalMessagesBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.UnitOfWorkBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.ChildContainerBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.Invoke()
   at NServiceBus.Pipeline.PipelineExecutor.Execute[T](BehaviorChain`1 pipelineAction, T context)
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg)
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message)
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message)
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action(TransactionSettings transactionSettings, TransactionOptions transactionOptions, MsmqUnitOfWork unitOfWork, MessageQueue receiveQueue, MessageQueue errorQueue, CircuitBreaker circuitBreaker, CriticalError criticalError, AutoResetEvent peekResetEvent, TimeSpan receiveTimeout, SemaphoreSlim throttlingSemaphore, Func`2 tryProcessMessage, Action`2 endProcessMessage)
```

**Comment by DavidBoike** [comment]
Re-closing, as this issue was fixed in NSB.Raven 4 (CoreV6) and may be nearly unfixable in V5 because of the overall strategy of how things are injected. In Raven4/Core6 we fix this by using the RavenSession() extension method to lazily create the session if necessary i.e. a handler in an endpoint where Saga/Outbox haven't already forced the issue.

https://github.com/Particular/docs.particular.net/pull/3558 updates the documentation to make this explicit. 

Since in most cases, the SharedSession API is not needed (it's really just for customizing the DocumentSession, and without access to any details about the message there's really not much of value that can be done there in the first place) so the fact that it's incompatible with the Outbox doesn't matter too much. We don't plan on fixing this for NSB.Raven 3 (CoreV5) unless a customer can present us with a reasonable use case with no workaround.
