### ISSUE TITLE
`BackwardsCompatibilityHelper` throws `NullReferenceException` when `Raven-Clr-Type` not present

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#73]
## Who's affected
All users using NServiceBus.RavenDB having documents in the database without the `Raven-Clr-Type` being set.

## Symptoms

So if we update https://github.com/Particular/docs.particular.net/tree/master/samples/saga/ravendb-custom-sagafinder/Version_5 to the newest raven bits we get a null reff here 
https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Internal/BackwardsCompatibilityHelper.cs#L18

stack trace:

```
System.InvalidOperationException: Could not convert document UniqueConstraints/OrderSagaDatas/PaymentTransactionId/dd1076ae-b49f-4c2c-9a37-c220a226a8ac to entity of type Raven.Client.UniqueConstraints.UniqueConstraintExtensions+ConstraintDocument ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.RavenDB.Internal.BackwardsCompatibilityHelper.<SupportOlderClrTypes>b__0(String id, RavenJObject doc, RavenJObject metadata) in c:\BuildAgent\work\c4d62ce02b983878\src\NServiceBus.RavenDB\Internal\BackwardsCompatibilityHelper.cs:line 20
   at Raven.Client.Document.DocumentConvention.GetClrType(String id, RavenJObject document, RavenJObject metadata) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\DocumentConvention.cs:line 615
   at Raven.Client.Document.InMemoryDocumentSessionOperations.ConvertToEntity(Type entityType, String id, RavenJObject documentFound, RavenJObject metadata) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 513
   --- End of inner exception stack trace ---
   at Raven.Client.Document.InMemoryDocumentSessionOperations.ConvertToEntity(Type entityType, String id, RavenJObject documentFound, RavenJObject metadata) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 546
   at Raven.Client.Document.InMemoryDocumentSessionOperations.TrackEntity(Type entityType, String key, RavenJObject document, RavenJObject metadata, Boolean noTracking) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 447
   at Raven.Client.Document.InMemoryDocumentSessionOperations.TrackEntity(Type entityType, JsonDocument documentFound) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 426
   at Raven.Client.Document.InMemoryDocumentSessionOperations.TrackEntity[T](JsonDocument documentFound) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 369
   at Raven.Client.Document.SessionOperations.MultiLoadOperation.ApplyTrackingIfNeeded[T](JsonDocument document) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\SessionOperations\MultiLoadOperation.cs:line 90
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Raven.Client.Document.SessionOperations.MultiLoadOperation.Complete[T]() in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\SessionOperations\MultiLoadOperation.cs:line 72
   at Raven.Client.Document.DocumentSession.LoadInternal[T](String[] ids, KeyValuePair`2[] includes) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\DocumentSession.cs:line 390
   at Raven.Client.Document.MultiLoaderWithInclude`1.Load(String[] ids) in c:\Builds\RavenDB-Stable-3.0\Raven.Client.Lightweight\Document\MultiLoaderWithInclude.cs:line 69
   at Raven.Client.UniqueConstraints.UniqueConstraintExtensions.LoadByUniqueConstraintInternal[T](IDocumentSession session, String propertyName, Object[] values) in c:\Builds\RavenDB-Stable-3.0\Bundles\Raven.Client.UniqueConstraints\UniqueConstraintExtensions.cs:line 101
   at Raven.Client.UniqueConstraints.UniqueConstraintExtensions.LoadByUniqueConstraint[T](IDocumentSession session, Expression`1 keySelector, Object value) in c:\Builds\RavenDB-Stable-3.0\Bundles\Raven.Client.UniqueConstraints\UniqueConstraintExtensions.cs:line 52
   at PaymentTransactionCompletedSagaFinder.FindBy(PaymentTransactionCompleted message) in c:\Code\docs.particular.net\samples\saga\ravendb-custom-sagafinder\Version_5\Sample\PaymentTransactionCompletedSagaFinder.cs:line 20
   at NServiceBus.Sagas.CustomFinderAdapter`2.Find(IBuilder builder, SagaFinderDefinition finderDefinition, LogicalMessage message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Sagas\CustomFinderAdapter.cs:line 16
```
![nullref](https://cloud.githubusercontent.com/assets/122666/8051281/ec77d446-0ebd-11e5-8b94-8e1f7dfe37f1.png)

**Comment by SimonCropp** [comment]
this also happens with RavenDB 2.5.2962 and NSB.Raven 2.2.0

**Comment by danielmarbach** [comment]
I backported it

**Comment by danielmarbach** [comment]
See hotfix-2.2.1, 2.1.1, 2.0.2
