### ISSUE TITLE
Could not load file or assembly Sparrow.dll

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.RavenDB#85]
## Symptoms

At startup a `TypeInitializationException: Could not load file or assembly Sparrow.dll` is thrown. See the full stack trace bellow.

The reason is:

* Raven uses Costura.
* `Raven.Abstractions.Logging.LogManager` exists in `Raven.Abstractions.dll`.
* `Raven.Abstractions` references `Sparrow.dll`.
* `Raven.Client.Lightweight.dll` is the one that is Costura merged when we try to 
set `CurrentLogManager` it will try to load `Sparrow.dll` before `Raven.Client.Lightweight`
has had a chance to plug into the assembly load pipeline.

## Resolution

Force a fake assembly load at startup by using `typeof` on a type that exists in `Raven.Client.Lightweigh.dll`

## Who's affected

Possibly anyone using the default settings (without passing in a custom DocumentStore) of NServiceBus.RavenDB.

---

```
System.TypeInitializationException was unhandled
  _HResult=-2146233036
  _message=The type initializer for 'Raven.Abstractions.Logging.LogManager' threw an exception.
  HResult=-2146233036
  IsTransient=false
  Message=The type initializer for 'Raven.Abstractions.Logging.LogManager' threw an exception.
  Source=Raven.Abstractions
  TypeName=Raven.Abstractions.Logging.LogManager
  StackTrace:
       at Raven.Abstractions.Logging.LogManager.set_CurrentLogManager(ILogManager value)
       at NServiceBus.Persistence.RavenDBPersistence.<.ctor>b__0(SettingsHolder s) in c:\Code\NServiceBus.RavenDB\src\NServiceBus.RavenDB\RavenDBPersistence.cs:line 21
       at NServiceBus.Persistence.PersistenceDefinition.ApplyDefaults(SettingsHolder settings) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Persistence\PersistenceDefinition.cs:line 93
       at NServiceBus.Persistence.PersistenceStartup.Run(Configure config) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Persistence\PersistenceStartup.cs:line 38
       at NServiceBus.Configure.<Initialize>b__6(IWantToRunBeforeConfigurationIsFinalized t) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 113
       at NServiceBus.Configure.<>c__DisplayClassc`1.<ActivateAndInvoke>b__b(Type t) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 183
       at NServiceBus.Configure.ForAllTypes[T](IEnumerable`1 types, Action`1 action) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 137
       at NServiceBus.Configure.ActivateAndInvoke[T](IList`1 types, Action`1 action) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 180
       at NServiceBus.Configure.Initialize() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 113
       at NServiceBus.Bus.Create(BusConfiguration configuration) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 19
       at Program.Main() in \Server\Program.cs:line 23
  InnerException: System.IO.FileNotFoundException
       _HResult=-2147024894
       _message=Could not load file or assembly 'Sparrow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=37f41c7f99471593' or one of its dependencies. The system cannot find the file specified.
       HResult=-2147024894
       IsTransient=false
       Message=Could not load file or assembly 'Sparrow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=37f41c7f99471593' or one of its dependencies. The system cannot find the file specified.
       Source=Raven.Abstractions
       FileName=Sparrow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=37f41c7f99471593
       FusionLog=Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  
\ravendb\Version_5\Server\bin\Debug\Server.exe
--- A detailed error log follows. 
```

**Comment by sfarmar** [comment]
Still there in 3.0.2

**Comment by SimonCropp** [comment]
@sfarmar please upload a repro

**Comment by sfarmar** [comment]
Repo here: https://github.com/sfarmar/supportcode/tree/master/85repo

HTH

**Comment by SimonCropp** [comment]
closing. see https://github.com/Particular/NServiceBus.RavenDB/issues/88
